name: testig-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Hello
      run: echo "hello"
    - name: bye
      run: |
        echo "bye"
        echo "bye bye"
  
